# Nice!Nano v2 Macropad Config

# Enable Bluetooth
CONFIG_BT=y
CONFIG_ZMK_BLE=y

# Enable USB (for wired use / flashing)
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y

# Enable encoder support
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Power management
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Dispaly support
CONFIG_I2C=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y